# Generated by Django 5.1.1 on 2024-09-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_endereco_pedido_itenspedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
