# Generated by Django 5.1.1 on 2024-09-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='id_pedido',
            new_name='id_pagamento',
        ),
    ]
