# Generated by Django 5.1.1 on 2024-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_rename_id_pedido_pagamento_id_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
